### Get all products
GET http://localhost:8080/api/products
Accept: application/json

### Get one product with an ID
GET http://localhost:8080/api/products/1
Accept: application/json

### Get product by name
GET http://localhost:8080/api/products/searchName
Content-Type: application/json

{
  "productName": "Test 1"
}

### Get products by price
GET http://localhost:8080/api/products/searchPrice
Content-Type: application/json

{
  "minPrice": 5,
  "maxPrice": 30
}

### Get products by Category
GET http://localhost:8080/api/products/searchCategory
Content-Type: application/json

{
  "categoryName": "Books22"
}

### Get products by supplier
GET http://localhost:8080/api/products/searchSupplier
Content-Type: application/json

{
 "supplierName": "Editions Palemon 29"
}

### Create product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Test 1",
  "description": "Test produit",
  "price": 25.00,
  "quantity": 1,
  "categoryId": 1,
  "supplierId": 1
}

### Update a product
PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
  "name": "Test 1",
  "description": "Test produit",
  "price": 25.00,
  "quantity": 1,
  "categoryId": 1,
  "supplierId": 1
}

### Delete a product
DELETE http://localhost:8080/api/products/2
Accept: application/json